name: /Users/ozanbaris/anaconda3/envs/nesl
channels:
  - defaults
  - conda-forge
dependencies:
  - anyio=4.2.0=py311hca03da5_0
  - appnope=0.1.4=pyhd8ed1ab_0
  - arrow=1.2.3=py311hca03da5_1
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backoff=2.2.1=py311hca03da5_1
  - beautifulsoup4=4.12.2=py311hca03da5_0
  - blas=1.0=openblas
  - blessed=1.20.0=py311hca03da5_0
  - boto3=1.34.82=py311hca03da5_0
  - botocore=1.34.82=py311hca03da5_0
  - bottleneck=1.3.7=py311hb9f6ed7_0
  - brotli=1.0.9=h80987f9_8
  - brotli-bin=1.0.9=h80987f9_8
  - brotli-python=1.0.9=py311h313beb8_8
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2024.6.2=hf0a4a13_0
  - certifi=2024.6.2=pyhd8ed1ab_0
  - cffi=1.16.0=py311h80987f9_1
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.1.7=py311hca03da5_0
  - comm=0.2.2=pyhd8ed1ab_0
  - contourpy=1.2.0=py311h48ca7d4_0
  - croniter=1.3.7=py311hca03da5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dateutils=0.6.12=py311hca03da5_0
  - debugpy=1.6.7=py311h313beb8_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - deepdiff=6.7.1=py311hb6e6a13_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - fastapi=0.103.0=py311hca03da5_0
  - filelock=3.13.1=py311hca03da5_0
  - fonttools=4.51.0=py311h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - fsspec=2024.3.1=py311hca03da5_0
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py311h40f64dc_0
  - h11=0.14.0=py311hca03da5_0
  - idna=3.7=py311hca03da5_0
  - importlib-metadata=7.1.0=pyha770c72_0
  - importlib_metadata=7.1.0=hd8ed1ab_0
  - inquirer=3.1.4=py311hca03da5_0
  - ipykernel=6.29.4=pyh57ce528_0
  - itsdangerous=2.2.0=py311hca03da5_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=py311hca03da5_0
  - jmespath=1.0.1=py311hca03da5_0
  - jpeg=9e=h80987f9_1
  - jupyter_client=8.6.2=pyhd8ed1ab_0
  - jupyter_core=5.7.2=py311hca03da5_0
  - kiwisolver=1.4.4=py311h313beb8_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libbrotlicommon=1.0.9=h80987f9_8
  - libbrotlidec=1.0.9=h80987f9_8
  - libbrotlienc=1.0.9=h80987f9_8
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.17=h80987f9_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libsodium=1.0.18=h27ca646_1
  - libtiff=4.5.1=h313beb8_0
  - libuv=1.44.2=h80987f9_0
  - libwebp-base=1.3.2=h80987f9_0
  - lightning=2.0.9.post0=py311hca03da5_0
  - lightning-cloud=0.5.57=py311hca03da5_0
  - lightning-utilities=0.9.0=py311hca03da5_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markdown-it-py=2.2.0=py311hca03da5_1
  - markupsafe=2.1.3=py311h80987f9_0
  - matplotlib=3.8.4=py311hca03da5_0
  - matplotlib-base=3.8.4=py311h7aedaa7_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_0
  - mdurl=0.1.0=py311hca03da5_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py311hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.1=py311hca03da5_0
  - ninja=1.10.2=hca03da5_5
  - ninja-base=1.10.2=h525c30c_5
  - numexpr=2.8.7=py311h6dc990b_0
  - numpy=1.26.4=py311he598dae_0
  - numpy-base=1.26.4=py311hfbfe69c_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=3.3.1=hfb2fe0b_0
  - ordered-set=4.1.0=py311hca03da5_0
  - orjson=3.9.15=py311hc9796cf_0
  - packaging=23.2=py311hca03da5_0
  - parso=0.8.4=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.3.0=py311h80987f9_0
  - pip=24.0=py311hca03da5_0
  - platformdirs=3.10.0=py311hca03da5_0
  - pooch=1.7.0=py311hca03da5_0
  - prompt-toolkit=3.0.47=pyha770c72_0
  - psutil=5.9.0=py311h80987f9_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=1.10.12=py311h80987f9_1
  - pygments=2.15.1=py311hca03da5_1
  - pyjwt=2.8.0=py311hca03da5_0
  - pyparsing=3.0.9=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.9=hb885b13_0
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - python-editor=1.0.4=pyhd3eb1b0_0
  - python-multipart=0.0.6=py311hca03da5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytorch=2.2.0=gpu_mps_py311hf322ab5_100
  - pytorch-lightning=2.0.3=py311hca03da5_0
  - pytz=2024.1=py311hca03da5_0
  - pyyaml=6.0.1=py311h80987f9_0
  - pyzmq=25.1.2=py311h313beb8_0
  - readchar=4.0.5=py311hca03da5_0
  - readline=8.2=h1a28f6b_0
  - rich=13.3.5=py311hca03da5_0
  - s3transfer=0.10.1=py311hca03da5_0
  - scipy=1.10.1=py311hc76d9b0_1
  - setuptools=69.5.1=py311hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sleef=3.5.1=h80987f9_2
  - sniffio=1.3.0=py311hca03da5_0
  - soupsieve=2.5=py311hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - starlette=0.27.0=py311hca03da5_0
  - starsessions=1.3.0=py311hca03da5_0
  - sympy=1.12=py311hca03da5_0
  - tk=8.6.14=h6ba3021_0
  - toolz=0.12.0=py311hca03da5_0
  - torchmetrics=1.1.2=py311hca03da5_0
  - tornado=6.3.3=py311h80987f9_0
  - tqdm=4.66.4=py311hb6e6a13_0
  - typing-extensions=4.11.0=py311hca03da5_0
  - typing_extensions=4.11.0=py311hca03da5_0
  - tzdata=2024a=h04d1e81_0
  - unicodedata2=15.1.0=py311h80987f9_0
  - urllib3=2.2.1=py311hca03da5_0
  - uvicorn=0.20.0=py311hca03da5_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - websocket-client=1.8.0=py311hca03da5_0
  - websockets=10.4=py311h80987f9_1
  - wheel=0.43.0=py311hca03da5_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zipp=3.19.2=pyhd8ed1ab_0
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.5=hd90d995_2
  - pip:
      - absl-py==2.1.0
      - accelerate==0.34.2
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - antropy==0.1.8
      - arch==7.2.0
      - astunparse==1.6.3
      - attrs==23.2.0
      - chronos==1.2.0
      - chronos-forecasting==1.5.0
      - clarabel==0.9.0
      - cloudpickle==3.0.0
      - cvxpy==1.5.2
      - datasets==3.1.0
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - dtaidistance==2.3.12
      - ecos==2.0.14
      - einops==0.8.0
      - einshape==1.0
      - farama-notifications==0.0.4
      - fastdtw==0.3.4
      - flatbuffers==24.12.23
      - frozenlist==1.4.1
      - gast==0.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gluonts==0.14.4
      - google-pasta==0.2.0
      - grpcio==1.69.0
      - gymnasium==0.29.1
      - h5py==3.11.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.30.2
      - hydra-core==1.3.2
      - inquirerpy==0.3.4
      - install==1.3.5
      - ipython==8.29.0
      - jax==0.4.28
      - jaxlib==0.4.28
      - jaxtyping==0.2.28
      - joblib==1.4.2
      - keras==3.8.0
      - libclang==18.1.1
      - llvmlite==0.43.0
      - markdown==3.7
      - ml-dtypes==0.4.0
      - momentfm==0.1
      - multidict==6.0.5
      - multiprocess==0.70.16
      - namex==0.0.8
      - nixtla==0.5.1
      - numba==0.60.0
      - omegaconf==2.3.0
      - opt-einsum==3.3.0
      - optree==0.14.0
      - osqp==0.6.7
      - pandas==2.1.4
      - patsy==0.5.6
      - pfzy==0.3.4
      - protobuf==5.27.2
      - pvlib==0.10.5
      - pyarrow==18.0.0
      - pyemd==1.0.0
      - qdldl==0.1.7.post3
      - regex==2024.5.15
      - requests==2.32.3
      - safetensors==0.4.3
      - sb3-contrib==2.3.0
      - scikit-learn==1.5.0
      - scs==3.2.4.post3
      - seaborn==0.13.2
      - sentry-sdk==2.7.1
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - smmap==5.0.1
      - soundfile==0.12.1
      - stable-baselines3==2.4.0a1
      - statsmodels==0.14.2
      - stochastic==0.6.0
      - supersmoother==0.4
      - tenacity==8.4.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.18.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.5.0
      - threadpoolctl==3.5.0
      - timesfm==1.2.3
      - tokenizers==0.21.1
      - traitlets==5.14.3
      - transformers==4.47.1
      - tsfeatures==0.4.5
      - tslearn==0.6.3
      - typeguard==2.13.3
      - typer==0.13.1
      - utilsforecast==0.1.11
      - wandb==0.18.7
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xxhash==3.5.0
      - yarl==1.9.4
prefix: /Users/ozanbaris/anaconda3/envs/nesl
